---
title: 'Prepare  experiment/analysis'
author: "Aleksej Zelezniak"
date: "`r Sys.Date()`"
output:
  html_notebook: default
  html_document:
    df_print: paged
---
```{r dir_set}
# use this to set the working directory to the location of the Rmd file if working in VSCode
#setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) 
```

```{r setup}
set.seed(1014)
options(digits = 3)

knitr::opts_chunk$set(
  dev = c("png"),
  echo=FALSE, warning=FALSE, message=FALSE
)


fun_name <- tools::file_path_sans_ext(basename(rstudioapi::getActiveDocumentContext()$path)) 
save_data_dir <- "output_files"
dir.create(save_data_dir, showWarnings = FALSE)
options(dplyr.print_min = 6, dplyr.print_max = 6)

figure_dir = "./output_plots"
dir.create(figure_dir, showWarnings = FALSE)


save_object <- function(object, save_data_dir) {
  object_name = deparse(substitute(object))
  file_name = paste(object_name, fun_name, "RData", sep = ".")
  file_path = paste(save_data_dir, file_name, sep="/")
  save(list = eval(object_name), file = file_path)
}

tidy_pca = function(x) {
  x.matrix <- x[,-1] %>% as.matrix()
  rownames(x.matrix) <- as.data.frame(x)[,1]
  return(x.matrix)
}


library(tidyverse)
library(patchwork)

```


```{r functions}

read_xvg <- function(file, ...) {
    readr::read_lines(file) %>%
      stringr::str_subset(pattern = "^(#|@).*", negate = TRUE) %>% 
      I() %>% 
      trimws() %>%
      readr::read_table(col_names = FALSE, progress = TRUE, ...) -> ds
  return(ds)
}

```